version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/wp-content/themes/vcp-hamburg-theme
    environment:
      WORDPRESS_DB_PASSWORD: supersecurepassword

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: supersecurepassword
